name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]  # Set this to your default branch
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install Trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'

      - name: Build
        run: |
          trunk build --release --public-url /${{ github.event.repository.name }}/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'  # Only deploy on the main branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist